### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by iosdev-republicofapps** [yahoo/hecate#13]
Hi,

Thank you so much for making Hecate available!  This is really generous of you and I really appreciate your hard work!  :-)

I'm trying to run some of your examples on an AWS Lightsail instance with 1 GB of RAM, but I get out of memory errors:
```
bash> ./distribute/bin/hecate -i examples/video.mp4 --generate_jpg --njpg 1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 HECATE Copyright 2016 Yahoo Inc.
   Licensed under the terms of the Apache 2.0 License.
   Developed by : Yale Song (yalesong@yahoo-inc.com)
   Built on  : 04:37:30 Apr 14 2018
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Killed

bash> dmesg
[37664845.289337] Out of memory: Kill process 16158 (hecate) score 862 or sacrifice child
[37664845.294055] Killed process 16158 (hecate) total-vm:1276288kB, anon-rss:872636kB, file-rss:336kB
```

So it looks like it's using 1.3 GB of memory and getting killed by the OOM system because the VM only has 1 GB of RAM.  Is it possible to tell hecate to use a max amount of memory, say 512 MB, to avoid this?

The reason I ask is that I want to run a job system on Heroku making video thumbnails for my app, but the cheapest Heroku dyno that has more than 1 GB is the Performance-M, which costs $250/month per dyno.  If I could limit the memory usage to 512 MB or less, I could run on a $50/month dyno.

Thanks,

Joel

**Comment by yalesong** [comment]
It looks like the OOM error happens when the library reads video frames and stores them into the memory (see [here](https://github.com/yahoo/hecate/blob/master/src/hecate/video_parser.cpp#L141-L162)). You might try either (1) increasing the step size when reading frames (the default is no frame skip) or (2) limiting the library to read only the first few seconds of the video. 

You can do (1) by setting the [step_sz](https://github.com/yahoo/hecate/blob/master/include/hecate/hecate.hpp#L57) parameter. I wouldn't recommend setting it to higher than 5. Too many frame skips will deteriorate the quality of shot boundary detection.

You can do (2) by setting the [max_duration](https://github.com/yahoo/hecate/blob/master/include/hecate/hecate.hpp#L65) parameter. Compared to (1), this has the benefit of not having to skip frames when reading videos, but it is (obviously) limiting because you are essentially ignoring the later part of the video.

I would start by increasing the step_sz parameter to 2 or 3. If that still doesn't sovle your problem, you can try limiting max_duration. Let me know how it goes!

**Comment by Cinerar** [comment]
When trying to experiment with step i recieve this error. 

OpenCV(3.4.1) Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /tmp/tmp.ouR8iVNauY/opencv-3.4.1/modules/core/src/matrix.cpp, line 464

**Comment by iosdev-republicofapps** [comment]
Thanks for the quick reply @yalesong !  I tried `--step=3 and --max_duration=120` and that seemed to work pretty well.

Is there a way to modify the code that it doesn't store the entire video in memory?  Like could it just store metadata for each frame after analyzing them, or could it just read and keep a sliding window of data/frames so that it keeps the frames live, but only for a section of [t-5,t+5] or something like that?

**Comment by yalesong** [comment]
The library clears the memory as soon as features are extracted from frames (see [here](https://github.com/yahoo/hecate/blob/master/src/hecate/video_parser.cpp#L30-L36)). The reason why we store them in the memory is to enable batch processing for feature extraction. A more robust way would be doing this with small batches. We've never found needs for this though as many modern computers have more than 4 GB of memory -- this of course doesn't consider cloud instances. We don't have any plan for the small batch extension, but you are more than welcome to contribute! :-).
