### ISSUE TITLE
generate jpg blocked

### ISSUE THREAD

**Issue by vc60er** [yahoo/hecate#17]
hi, @yalesong 

When i use hecate to generate jpg, but never finished the process. seems blocked at here

  printf("VideoParser: VideoCapture\n");
  **VideoCapture vr( in_video );**
  printf("VideoParser: vr.isOpened\n");
  if( !vr.isOpened() ) {
    return -1;
  }

my environment is:  
centos6.6, opencv3.1 ffmpeg2.8.15

 hecate]# ./distribute/bin/hecate -i examples/video_sum.mp4  --generate_jpg  -o $PWD --debug

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 HECATE Copyright 2016 Yahoo Inc.
   Licensed under the terms of the Apache 2.0 License.
   Developed by : Yale Song (yalesong@yahoo-inc.com)
   Built on  : 10:10:35 Nov  6 2018
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
run_hecate: Video segmentation and keyframe extraction
run_hecate: PARSE
VideoParser: examples/video_sum.mp4
VideoParser: read_video("examples/video_sum.mp4", 
        step_sz=1, max_duration=-1.00, max_frm_len=160, ignore_rest=0)
VideoParser: VideoCapture

**Comment by yalesong** [comment]
Sorry for the delay in response. How long is your video? Could you run `ffprobe -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1examples/video_sum/mp4` and copy&paste the output here?

**Comment by vc60er** [comment]
ffprobe -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 examples/video_sum.mp4
ffprobe version 2.8.15 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-11)
  configuration: --enable-gpl --enable-libx264 --enable-libmp3lame
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'examples/video_sum.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.36.100
  Duration: 00:00:16.02, start: 0.000000, bitrate: 362 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 320x240, 295 kb/s, 29.05 fps, 59.94 tbr, 11968 tbn, 59.84 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 22050 Hz, stereo, fltp, 63 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
459

**Comment by yalesong** [comment]
I initially suspected the video is too long; this doesn't seem to be the case. Can you share the video with me so that I can take a look?

**Comment by mkummer225** [comment]
@yalesong is there a current limit on the maximum length of a video?

I tried an ~25min video but it seemed to inf. loop & hold my CPU at 100% for about 20 mins before I shut it down. An ~5 min video takes about 30 seconds (just generating a single jpg thumbnail)

**Comment by yalesong** [comment]
@mkummer225, currently there isn't a limit on the maximum video length as it depends on the available size of memory in each machine (frames are stored in memory to find good thumbnails).  If your goal is to just extract a single jpg thumbnail, I would suggest setting `max_duration` to something like 300 seconds. You can do this by passing `--max_duration 300` in input command (it changes [this variable](https://github.com/yahoo/hecate/blob/master/include/hecate/hecate.hpp#L164)). Note that this doesn't mean any content after the 5 minute mark is ignored; it just reads frames less frequently so that the number of frames read equals 5 minutes. Once this is set, the program will adjust the number of frames to skip when reading the video, as shown in [this code snippet](https://github.com/yahoo/hecate/blob/89b75ccceac2388597648a2a476b0a0716bb06ab/src/hecate/video_parser.cpp#L117-L133)
