### ISSUE TITLE
result about paper

### ISSUE THREAD

**Issue by leeqiaogithub** [yahoo/hecate#20]
When I verified the results of the paper, the video key frame obtained according to the code you provided was inconsistent with your results.for example, the file /YahooScreen/thumbnail-master/results/ours_unsupervised/951f7361-5c20-3d98-bc70-a4a9f43d04d7.txt shows "5906  8472  7800  3741  2399  7947" .but when i run 951f7361-5c20-3d98-bc70-a4a9f43d04d7.mp4 i just got "2715 1519 3193 1103 3442 ".
so i want to know what is the difference between your test code and this exposed code.

**Comment by yalesong** [comment]
Since the CIKM 2016 paper, we've made numerous modifications to this software package, adding new features (GIF extraction and video summarization) and perf optimizations. So the results we've shared [in the other repo](https://github.com/yalesong/thumbnail) might be different from what you get using the software in this repo.
